### ISSUE TITLE
Easy environment variable fix for windows

### ISSUE THREAD

**Issue by cgdougm** [jzillmann/template-electron-svelte#2]
Everything works smooth.

I just had one item that might work better for Windows: use the "cross-env" package for the "NODE_ENV=development" for the 'pure-electron-dev' script.

ie. 

    npm i cross-env

and in `package.json` change

    "pure-electron-dev": "NODE_ENV=development electron .",

to

    "pure-electron-dev": "cross-env NODE_ENV=development electron .",

[Cross-env package](https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows?newreg=6c42c5e7fd0144ff87d57a4a479a1e05)

Thanks!

**Comment by jzillmann** [comment]
Thanks @cgdougm , i've updated the template!
