### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by eightfivelabs** [jzillmann/template-electron-svelte#4]
Hi, I have been trying to figure out using the `ipcRenderer` process with svelte in eletron. I was also having the same issue on https://github.com/Rich-Harris/svelte-template-electron/issues/3#issue-633016576
If I clone the repo and add the following to App.svelte 
```js 
<script> const {ipcRenderer} = require("electron"); </script> 
``` 
it provides the error `Uncaught ReferenceError: require is not defined at instance (App.svelte:2)` Any thoughts on how to resolve?

Adding the below fixes this, but that seems to be generally not recommended by electron docs.
```
    webPreferences: {
      nodeIntegration: true
    }
```

**Comment by jzillmann** [comment]
Hey @eightfivelabs ,
so far i always solved it with `nodeIntegration=true` as well. I guess there might be another way on the build tool (rollup, webpack, etc) level but i didn't dived into it yet!

**Comment by eightfivelabs** [comment]
Thanks @jzillmann
